In [1]:
import numpy as np

##### 1. How many negative numbers are there?

In [65]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [32]:
type(a)

numpy.ndarray

In [29]:
(a[a<0])
    

array([-2, -1, -6, -7])

In [30]:
len(a[a<0])

4

In [ ]:
# There are 4 negative numbers.

##### 2. How many positive numbers are there?

In [33]:
len(a[a>0])

5

In [ ]:
# There are 5 positive numbers.

##### 3. How many even positive numbers are there?

In [69]:
ep_output = a
for i in ep_output:
    if i % 2 == 0:
        ep_output


In [70]:
ep_output

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [67]:
type(a)

numpy.ndarray

In [78]:
a[(a%2 == 0) & (a>0)]

array([ 4, 10, 12])

In [ ]:
# There are 3 even positive numbers.

##### If you were to add 3 to each data point, how many positive numbers would there be?

In [85]:
a_plus_three = a + 3

a_plus_three

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [90]:
a_plus_three[a_plus_three > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [91]:
len(a_plus_three[a_plus_three > 0])

10

In [92]:
# If you add 3 to each data point, 
## there are 10 positive numbers

##### 5. If you squared each number, what would the new mean and standard deviation be?

In [93]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [94]:
a.mean(), a.std()

(3.0, 8.06225774829855)

In [96]:
a_squared = a*a

a_squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [97]:
a_squared.mean(), a_squared.std()

(74.0, 144.0243035046516)

In [98]:
# The original mean and std are:
# mean: 3.0
# std: 8.06225774829855

# If you square each number, 
# the new mean is: 74.0,
# the new std is: 144.0243035046516

##### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set.

In [100]:
center = a - a.mean()

center

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [103]:
# The centered data set is:
# array([  1.,   7.,   9.,  20.,  -5.,
#        -4.,  -3.,  -3.,  -3.,  -9.,   0., -10.])

##### Calculate the z-score for each data point

In [105]:
z_score = (a - a.mean())/a.std()

z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [106]:
# The z-score for each data point is:
#array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469,
#       -0.62017367, -0.49613894, -0.3721042 , -0.3721042 ,
#        -0.3721042 , -1.11631261, 0.        , -1.24034735])

##### 

##### 

##### 

### More Numpy Practice

In [108]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators
## to determine the following:

##### Convert a to an array

In [112]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

type(a)

list

In [113]:
b = np.array(a)

b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
type(b)

numpy.ndarray

##### Exercise 1. Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [115]:
sum_of_a = b.sum()

sum_of_a

55

##### Exercise 2. Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [116]:
min_of_a = b.min()

min_of_a

1

##### Exercise 3. Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [117]:
max_of_a = b.max()

max_of_a

10

##### Exercise 4. Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [118]:
mean_of_a = b.mean()

mean_of_a

5.5

##### Exercise 5. Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [120]:
product_of_a = np.prod(b)

product_of_a

3628800

##### Exercise 6. Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [122]:
squares_of_a = b*b

squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

##### Exercise 7. Make a variable named odds_in_a. It should hold only the odd numbers

In [125]:
odds_in_a = b[b % 2 != 0]

odds_in_a

array([1, 3, 5, 7, 9])

##### Exercise 8. Make a variable named evens_in_a. It should hold only the evens.

In [126]:
evens_in_a = b[b % 2 == 0]

evens_in_a

array([ 2,  4,  6,  8, 10])

##### 

## Setup 2
Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [127]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

##### Exercise 1 - refactor the following to use numpy. 
##### Use sum_of_b as the variable. 
##### **Hint, you'll first need to make sure that 
##### the "b" variable is a numpy array**

In [133]:
c = np.array(b)

c

array([[3, 4, 5],
       [6, 7, 8]])

In [134]:
sum_of_b = 0
for row in c:
    sum_of_b += sum(row)
    
sum_of_b

33

##### Exercise 2. Refactor the following to use numpy. 

In [136]:
min_of_b = min(c[0]) if min(c[0]) <= min(c[1]) else min(c[1])

min_of_b

3

##### Exercise 3. Refactor the following maximum calculation to find the answer with numpy.

In [138]:
max_of_b = max(c[0]) if max(c[0]) >= max(c[1]) else max(c[1])

max_of_b

8

##### Exercise 4. Refactor the following using numpy to find the mean of b

In [139]:
mean_of_b = (sum(c[0]) + sum(c[1])) / (len(c[0]) + len(c[1]))

mean_of_b

5.5

##### Exercise 5. Refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [141]:
product_of_b = 1
for row in c:
    for number in row:
        product_of_b *= number
        
product_of_b

20160

##### Exercise 6. Refactor the following to use numpy to find the list of squares 

In [143]:
squares_of_b = []
for row in c:
    for number in row:
        squares_of_b.append(number**2)
        
squares_of_b

[9, 16, 25, 36, 49, 64]

##### Exercise 7. Refactor using numpy to determine the odds_in_b

In [144]:
odds_in_b = []
for row in c:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
odds_in_b

[3, 5, 7]

##### Exercise 8. Refactor the following to use numpy to filter only the even numbers

In [145]:
evens_in_b = []
for row in c:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
evens_in_a

array([ 2,  4,  6,  8, 10])

##### Exercise 9. Print out the shape of the array b.

In [146]:
print(c.shape)

(2, 3)


##### Exercise 10. Transpose the array b.

In [147]:
np.transpose(c)

array([[3, 6],
       [4, 7],
       [5, 8]])

##### Exercise 11. Reshape the array b to be a single list of 6 numbers. (1 x 6)

In [149]:
np.reshape(c, (1, 6))

array([[3, 4, 5, 6, 7, 8]])

##### Exercise 12. Reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [150]:
np.reshape(c, (6, 1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3

In [153]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that
# the "c" variable is a numpy array prior to 
# using numpy array methods.

In [154]:
d = np.array(c)

d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### Exercise 1. Find the min, max, sum, and product of c.

In [156]:
d.min(), d.max(), d.sum(), np.prod(c)

(1, 9, 45, 362880)

##### Exercise 2. Determine the standard deviation of c.

In [157]:
d.std()

2.581988897471611

##### Exercise 3. Determine the variance of c.

In [159]:
np.var(d)

6.666666666666667

##### Exercise 4. Print out the shape of the array c

In [158]:
np.shape(d)

(3, 3)

##### Exercise 5. Transpose c and print out transposed result.

In [163]:
print(np.transpose(d))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


##### Exercise 6. Get the dot product of the array c with c.

In [164]:
np.dot(d, d)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

##### Exercise 7. Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [166]:
d_x_d = d * np.transpose(d)
d_x_d

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [167]:
d_x_d.sum()

261

##### Exercise 8. Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [168]:
np.prod(d_x_d)

131681894400

## Setup 4

In [169]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

##### Exercise 1. Find the sine of all the numbers in d

##### Exercise 2. Find the cosine of all the numbers in d

##### Exercise 3. Find the tangent of all the numbers in d

##### Exercise 4. Find all the negative numbers in d

##### Exercise 5. Find all the positive numbers in d

##### Exercise 6. Return an array of only the unique numbers in d.

##### Exercise 7. Determine how many unique numbers there are in d.

##### Exercise 8. Print out the shape of d.

##### Exercise 9. Transpose and then print out the shape of d.

##### Exercise 10. Reshape d into an array of 9 x 2